/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr_bsit1b_it04_jqjz;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import hr_bsit1b_it04_jqjz.jqjzConnect;
import java.awt.Color;
/**
 *
 * @author JLZapanta;
 */
public class frmAddEmployee extends javax.swing.JFrame {
    private Statement jqjzstatement;
    public String strjqjzEmpID,strjqjzEmpPass,strjqjzEmpEmail,strjqjzEmpName,strjqjzEmpAddress,strjqjzEmpMobile;                
    public int jqjznumberOfRows;
    jqjzConnect jqjzC = new jqjzConnect();
    Connection jqjzconn;
    PreparedStatement jqjzpreparedStatement;
    String jqjzstrSQL;
    ResultSet jqjzrs;
    /**
     * Creates new form frmUserSignUpJQJZ
     */
    public frmAddEmployee() throws SQLException{
        initComponents();
        makeStatement();
        setTitle("Employee Information");
        this.setSize(1366,768); //set display of the current jframe form to 1366x768 resolution
    }
    public Statement makeStatement() throws SQLException{
    jqjzConnect c = new jqjzConnect();
    Connection jqjzconn = c.makeConnection();
    jqjzstatement = jqjzconn.createStatement();
    return jqjzstatement;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jqjzPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbljqjzEmployeeID = new javax.swing.JLabel();
        txtjqjzEmpID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtjqjzEmpName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbljqjzLName = new javax.swing.JLabel();
        lbljqjzFName = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtjqjzEmpEmail = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtjqjzEmpMobile = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lbljqjzMName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbljqjzPassword = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        lbljqjzEmail = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        pwjqjzEmpPass = new javax.swing.JPasswordField();
        btnjqjzUpdate = new javax.swing.JLabel();
        btnjqjzProceed = new javax.swing.JLabel();
        txtjqjzEmpAddress = new javax.swing.JTextField();
        btnjqjzSave = new javax.swing.JLabel();
        btnjqjzSearch = new javax.swing.JLabel();
        btnjqjzDelete = new javax.swing.JLabel();
        btnjqjzClear = new javax.swing.JLabel();
        lbljqjzUserInfo = new javax.swing.JLabel();
        lbljqjzIcon = new javax.swing.JLabel();
        lbljqjzApex = new javax.swing.JLabel();

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(175, 102, 37));
        kGradientPanel1.setkGradientFocus(700);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 223, 171));

        jqjzPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbljqjzEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzEmployeeID.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzEmployeeID.setText("Employee ID");

        txtjqjzEmpID.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzEmpID.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzEmpID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzEmpID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/id.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator1.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        txtjqjzEmpName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzEmpName.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzEmpName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzEmpName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/user.png"))); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator3.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        lbljqjzLName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzLName.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzLName.setText("Employee Name");

        lbljqjzFName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzFName.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzFName.setText("Employee Address");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/user.png"))); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator4.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        txtjqjzEmpEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzEmpEmail.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzEmpEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzEmpEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jSeparator5.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator5.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        txtjqjzEmpMobile.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzEmpMobile.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzEmpMobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzEmpMobile.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/user.png"))); // NOI18N

        lbljqjzMName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzMName.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzMName.setText("Employee Mobile");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/password.png"))); // NOI18N

        lbljqjzPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzPassword.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzPassword.setText("Password");

        jSeparator6.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator6.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/email.png"))); // NOI18N

        lbljqjzEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzEmail.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzEmail.setText("E-mail Address");

        jSeparator7.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator7.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        pwjqjzEmpPass.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pwjqjzEmpPass.setForeground(new java.awt.Color(159, 105, 61));
        pwjqjzEmpPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwjqjzEmpPass.setBorder(null);

        btnjqjzUpdate.setBackground(new java.awt.Color(178, 121, 74));
        btnjqjzUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjqjzUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnjqjzUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjqjzUpdate.setText("Update Record");
        btnjqjzUpdate.setOpaque(true);
        btnjqjzUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjzUpdateMouseClicked(evt);
            }
        });

        btnjqjzProceed.setBackground(new java.awt.Color(255, 255, 255));
        btnjqjzProceed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjqjzProceed.setForeground(new java.awt.Color(178, 121, 74));
        btnjqjzProceed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjqjzProceed.setText("Proceed to Dashboard");
        btnjqjzProceed.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(178, 121, 74)));
        btnjqjzProceed.setOpaque(true);

        txtjqjzEmpAddress.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzEmpAddress.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzEmpAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzEmpAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        btnjqjzSave.setBackground(new java.awt.Color(178, 121, 74));
        btnjqjzSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjqjzSave.setForeground(new java.awt.Color(255, 255, 255));
        btnjqjzSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjqjzSave.setText("Save Record");
        btnjqjzSave.setOpaque(true);
        btnjqjzSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjzSaveMouseClicked(evt);
            }
        });

        btnjqjzSearch.setBackground(new java.awt.Color(178, 121, 74));
        btnjqjzSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjqjzSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnjqjzSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjqjzSearch.setText("Search Record");
        btnjqjzSearch.setOpaque(true);
        btnjqjzSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjzSearchMouseClicked(evt);
            }
        });

        btnjqjzDelete.setBackground(new java.awt.Color(178, 121, 74));
        btnjqjzDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjqjzDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnjqjzDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjqjzDelete.setText("Delete Record");
        btnjqjzDelete.setOpaque(true);
        btnjqjzDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjzDeleteMouseClicked(evt);
            }
        });

        btnjqjzClear.setBackground(new java.awt.Color(178, 121, 74));
        btnjqjzClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjqjzClear.setForeground(new java.awt.Color(255, 255, 255));
        btnjqjzClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjqjzClear.setText("Clear Entries");
        btnjqjzClear.setOpaque(true);
        btnjqjzClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjzClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                .addComponent(txtjqjzEmpAddress)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtjqjzEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbljqjzLName)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjqjzEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbljqjzEmployeeID)
                    .addComponent(lbljqjzFName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator7)
                                    .addComponent(txtjqjzEmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtjqjzEmpMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pwjqjzEmpPass, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbljqjzMName))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbljqjzEmail)
                            .addComponent(lbljqjzPassword))
                        .addGap(222, 222, 222))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnjqjzProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnjqjzSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnjqjzSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnjqjzUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnjqjzDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnjqjzClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbljqjzEmployeeID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtjqjzEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbljqjzMName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtjqjzEmpMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbljqjzEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtjqjzEmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(lbljqjzPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(pwjqjzEmpPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtjqjzEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbljqjzLName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lbljqjzFName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtjqjzEmpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnjqjzSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnjqjzSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnjqjzUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnjqjzDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnjqjzClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnjqjzProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbljqjzUserInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljqjzUserInfo.setForeground(new java.awt.Color(159, 105, 61));
        lbljqjzUserInfo.setText("Employee's Information");

        lbljqjzIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/logo2_trsp.png"))); // NOI18N

        lbljqjzApex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/company2_trsp.png"))); // NOI18N

        javax.swing.GroupLayout jqjzPanel1Layout = new javax.swing.GroupLayout(jqjzPanel1);
        jqjzPanel1.setLayout(jqjzPanel1Layout);
        jqjzPanel1Layout.setHorizontalGroup(
            jqjzPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jqjzPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbljqjzUserInfo)
                .addGap(240, 240, 240))
            .addGroup(jqjzPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jqjzPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(lbljqjzIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbljqjzApex)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jqjzPanel1Layout.setVerticalGroup(
            jqjzPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jqjzPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jqjzPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbljqjzApex, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbljqjzIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lbljqjzUserInfo)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jqjzPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jqjzPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjqjzSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzSaveMouseClicked
        // TODO add your handling code here:
        if(txtjqjzEmpID.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Employee ID!");
             txtjqjzEmpID.requestFocus();
         }
         else if(txtjqjzEmpName.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Employee Name!");
             txtjqjzEmpName.requestFocus();
         }
         else if(txtjqjzEmpAddress.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Employee Address!");
             txtjqjzEmpAddress.requestFocus();
         }
          else if(txtjqjzEmpMobile.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Employee Mobile!");
             txtjqjzEmpMobile.requestFocus();
         }
          else if(txtjqjzEmpEmail.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter E-mail Address!");
             txtjqjzEmpEmail.requestFocus();
         }
          else if(pwjqjzEmpPass.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Employee Password!");
             pwjqjzEmpPass.requestFocus();
         }
         else{
             try {
                //intID = Integer.parseInt(txtID.getText());
                strjqjzEmpID = txtjqjzEmpID.getText();
                strjqjzEmpName = txtjqjzEmpName.getText();
                strjqjzEmpAddress = txtjqjzEmpAddress.getText();
                strjqjzEmpMobile = txtjqjzEmpMobile.getText();
                strjqjzEmpEmail = txtjqjzEmpEmail.getText();
                strjqjzEmpPass = pwjqjzEmpPass.getText();
                
                jqjzconn = jqjzC.makeConnection();
                jqjzstrSQL = "SELECT COUNT(*) AS totRec FROM tbljqjz_employees WHERE Employee_id=?";
                jqjzpreparedStatement = jqjzconn.prepareStatement(jqjzstrSQL);
                jqjzpreparedStatement.setString(1,strjqjzEmpID);
                jqjzrs = jqjzpreparedStatement.executeQuery();
                
                while (jqjzrs.next()) {
                    jqjznumberOfRows = jqjzrs.getInt("totRec");
                    //JOptionPane.showMessageDialog(null, numberOfRows);
                }
                if(jqjznumberOfRows == 1){
                    JOptionPane.showMessageDialog(null, "Record Already Exist!");
                }
                else {
                    String jqjzinsertTableSQL = "INSERT INTO tbljqjz_employees"
                    + "(Employee_id, Employee_password, Employee_email, Employee_name, Employee_address, Employee_mobile) VALUES"
                    + "(?,?,?,?,?,?)";
                    jqjzpreparedStatement = jqjzconn.prepareStatement(jqjzinsertTableSQL);
                    jqjzpreparedStatement.setString(1, strjqjzEmpID);
                    jqjzpreparedStatement.setString(2, strjqjzEmpPass);
                    jqjzpreparedStatement.setString(3, strjqjzEmpEmail);
                    jqjzpreparedStatement.setString(4, strjqjzEmpName);
                    jqjzpreparedStatement.setString(5, strjqjzEmpAddress);
                    jqjzpreparedStatement.setString(6, strjqjzEmpMobile);
                    
                    // execute insert SQL stetement
                    jqjzpreparedStatement .executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Successfully Saved!");
                }
            }
            catch(SQLException jqjzE){
                System.out.println("Failed");
                jqjzE.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnjqjzSaveMouseClicked

    private void btnjqjzSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzSearchMouseClicked
        // TODO add your handling code here:
        if(txtjqjzEmpID.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Employee ID!");
             txtjqjzEmpID.requestFocus();
         }
        else{
             try {
                strjqjzEmpID = txtjqjzEmpID.getText();
                jqjzconn = jqjzC.makeConnection();
                jqjzstrSQL = "SELECT COUNT(*) as totRec FROM tbljqjz_employees WHERE Employee_id=?";
                jqjzpreparedStatement = jqjzconn.prepareStatement(jqjzstrSQL);
                jqjzpreparedStatement.setString(1,strjqjzEmpID);
                jqjzrs = jqjzpreparedStatement.executeQuery();
                
                while (jqjzrs.next()) {
                     //JOptionPane.showMessageDialog(null, numberOfRows);
                    jqjznumberOfRows = (jqjzrs.getInt("totRec"));
                }
                if(jqjznumberOfRows == 1){
                    jqjzstrSQL = "SELECT * FROM tbljqjz_employees WHERE Employee_id=?";
                    jqjzpreparedStatement = jqjzconn.prepareStatement(jqjzstrSQL);
                    jqjzpreparedStatement.setString(1,strjqjzEmpID);

                    jqjzrs = jqjzpreparedStatement.executeQuery();
                    
                    while(jqjzrs.next()){
                        //JOptionPane.showMessageDialog(null, numberOfRows);
                        txtjqjzEmpID.setText(jqjzrs.getString("Employee_id"));
                        txtjqjzEmpName.setText(jqjzrs.getString("Employee_name"));
                        txtjqjzEmpAddress.setText(jqjzrs.getString("Employee_address"));
                        txtjqjzEmpMobile.setText(jqjzrs.getString("Employee_mobile"));
                        txtjqjzEmpEmail.setText(jqjzrs.getString("Employee_email"));
                        pwjqjzEmpPass.setText(jqjzrs.getString("Employee_password"));
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Record Does Not Exist!");
                    txtjqjzEmpID.setText("");
                    txtjqjzEmpName.setText("");
                    txtjqjzEmpAddress.setText("");
                    txtjqjzEmpMobile.setText("");
                    txtjqjzEmpEmail.setText("");
                    pwjqjzEmpPass.setText("");
                }
            }
            catch(SQLException jqjzE){
                System.out.println("Failed");
                jqjzE.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnjqjzSearchMouseClicked

    private void btnjqjzUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzUpdateMouseClicked
        // TODO add your handling code here:
        if(txtjqjzEmpID.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Employee ID!");
             txtjqjzEmpID.requestFocus();
        }
        else{
            try{
                strjqjzEmpID = txtjqjzEmpID.getText();
                strjqjzEmpName = txtjqjzEmpName.getText();
                strjqjzEmpAddress = txtjqjzEmpAddress.getText();
                strjqjzEmpMobile = txtjqjzEmpMobile.getText();
                strjqjzEmpEmail = txtjqjzEmpEmail.getText();
                strjqjzEmpPass = pwjqjzEmpPass.getText();
                
                jqjzconn = jqjzC.makeConnection();
                String jqjzupdateTableSQL = "UPDATE tbljqjz_employees SET Employee_password = ?,Employee_email = ?,Employee_name = ?,Employee_address = ?,"
                        + "Employee_mobile = ? WHERE Employee_id = ?";
                jqjzpreparedStatement = jqjzconn.prepareStatement(jqjzupdateTableSQL);
                    jqjzpreparedStatement.setString(1, strjqjzEmpPass);
                    jqjzpreparedStatement.setString(2, strjqjzEmpEmail);
                    jqjzpreparedStatement.setString(3, strjqjzEmpName);
                    jqjzpreparedStatement.setString(4, strjqjzEmpAddress);
                    jqjzpreparedStatement.setString(5, strjqjzEmpMobile);
                    jqjzpreparedStatement.setString(6, strjqjzEmpID);
                    // execute update SQL stetement
                    jqjzpreparedStatement.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Successfully Updated!");
            }
            catch(SQLException jqjzE){
                System.out.println("Failed");
                jqjzE.printStackTrace();
            }
        } 
    }//GEN-LAST:event_btnjqjzUpdateMouseClicked

    private void btnjqjzDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzDeleteMouseClicked
        // TODO add your handling code here:
        if(txtjqjzEmpID.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Employee ID!");
             txtjqjzEmpID.requestFocus();
        }
        else{
            try{
                strjqjzEmpID = txtjqjzEmpID.getText();

                jqjzconn = jqjzC.makeConnection();
                jqjzstrSQL = "DELETE FROM tbljqjz_employees WHERE Employee_id = ?";;
                jqjzpreparedStatement = jqjzconn.prepareStatement(jqjzstrSQL);
                    jqjzpreparedStatement.setString(1, strjqjzEmpID);
                    // execute delete SQL stetement
                    jqjzpreparedStatement .executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Successfully Deleted!");
                    txtjqjzEmpID.setText("");
                    txtjqjzEmpName.setText("");
                    txtjqjzEmpAddress.setText("");
                    txtjqjzEmpMobile.setText("");
                    txtjqjzEmpEmail.setText("");
                    pwjqjzEmpPass.setText("");                    
            }
            catch(SQLException jqjzE){
                System.out.println("Failed");
                jqjzE.printStackTrace();
            }
        } 
    }//GEN-LAST:event_btnjqjzDeleteMouseClicked

    private void btnjqjzClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzClearMouseClicked
        // TODO add your handling code here:
        txtjqjzEmpID.setText("");
        txtjqjzEmpName.setText("");
        txtjqjzEmpAddress.setText("");
        txtjqjzEmpMobile.setText("");
        txtjqjzEmpEmail.setText("");
        pwjqjzEmpPass.setText("");
    }//GEN-LAST:event_btnjqjzClearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmAddEmployee().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmAddEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnjqjzClear;
    private javax.swing.JLabel btnjqjzDelete;
    private javax.swing.JLabel btnjqjzProceed;
    private javax.swing.JLabel btnjqjzSave;
    private javax.swing.JLabel btnjqjzSearch;
    private javax.swing.JLabel btnjqjzUpdate;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel jqjzPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lbljqjzApex;
    private javax.swing.JLabel lbljqjzEmail;
    private javax.swing.JLabel lbljqjzEmployeeID;
    private javax.swing.JLabel lbljqjzFName;
    private javax.swing.JLabel lbljqjzIcon;
    private javax.swing.JLabel lbljqjzLName;
    private javax.swing.JLabel lbljqjzMName;
    private javax.swing.JLabel lbljqjzPassword;
    private javax.swing.JLabel lbljqjzUserInfo;
    private javax.swing.JPasswordField pwjqjzEmpPass;
    private javax.swing.JTextField txtjqjzEmpAddress;
    private javax.swing.JTextField txtjqjzEmpEmail;
    private javax.swing.JTextField txtjqjzEmpID;
    private javax.swing.JTextField txtjqjzEmpMobile;
    private javax.swing.JTextField txtjqjzEmpName;
    // End of variables declaration//GEN-END:variables
}
