/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr_bsit1b_it04_jqjz;

import java.sql.SQLException;

/**
 *
 * @author JLZapanta;
 */
public class frmHomeJQJZ extends javax.swing.JFrame {

    /**
     * Creates new form frmHomeJQJZ
     */
    public frmHomeJQJZ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        pnljqjz_inputDashBoard = new javax.swing.JPanel();
        btnjqjz_inputDashBoard = new javax.swing.JLabel();
        lbljqjz_inputDashboard = new javax.swing.JLabel();
        pnljqjz_recordDashBoard = new javax.swing.JPanel();
        btnjqjz_recordDashBoard = new javax.swing.JLabel();
        lbljqjz_recordDashboard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        kGradientPanel1.setBackground(new java.awt.Color(235, 218, 204));
        kGradientPanel1.setkEndColor(new java.awt.Color(242, 224, 210));
        kGradientPanel1.setkGradientFocus(700);
        kGradientPanel1.setkStartColor(new java.awt.Color(235, 218, 204));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        pnljqjz_inputDashBoard.setBackground(new java.awt.Color(235, 218, 204));
        pnljqjz_inputDashBoard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnjqjz_inputDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/output_300px.png"))); // NOI18N
        btnjqjz_inputDashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjz_inputDashBoardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnjqjz_inputDashBoardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnjqjz_inputDashBoardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnjqjz_inputDashBoardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnjqjz_inputDashBoardMouseReleased(evt);
            }
        });

        lbljqjz_inputDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbljqjz_inputDashboard.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjz_inputDashboard.setText("INPUT DASHBOARD");

        javax.swing.GroupLayout pnljqjz_inputDashBoardLayout = new javax.swing.GroupLayout(pnljqjz_inputDashBoard);
        pnljqjz_inputDashBoard.setLayout(pnljqjz_inputDashBoardLayout);
        pnljqjz_inputDashBoardLayout.setHorizontalGroup(
            pnljqjz_inputDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnljqjz_inputDashBoardLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lbljqjz_inputDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnljqjz_inputDashBoardLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(btnjqjz_inputDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pnljqjz_inputDashBoardLayout.setVerticalGroup(
            pnljqjz_inputDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnljqjz_inputDashBoardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbljqjz_inputDashboard)
                .addGap(47, 47, 47)
                .addComponent(btnjqjz_inputDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnljqjz_recordDashBoard.setBackground(new java.awt.Color(235, 218, 204));
        pnljqjz_recordDashBoard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnjqjz_recordDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/input_300px.png"))); // NOI18N
        btnjqjz_recordDashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjz_recordDashBoardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnjqjz_recordDashBoardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnjqjz_recordDashBoardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnjqjz_recordDashBoardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnjqjz_recordDashBoardMouseReleased(evt);
            }
        });

        lbljqjz_recordDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbljqjz_recordDashboard.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjz_recordDashboard.setText("RECORD DASHBOARD");

        javax.swing.GroupLayout pnljqjz_recordDashBoardLayout = new javax.swing.GroupLayout(pnljqjz_recordDashBoard);
        pnljqjz_recordDashBoard.setLayout(pnljqjz_recordDashBoardLayout);
        pnljqjz_recordDashBoardLayout.setHorizontalGroup(
            pnljqjz_recordDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnljqjz_recordDashBoardLayout.createSequentialGroup()
                .addGroup(pnljqjz_recordDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnljqjz_recordDashBoardLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnjqjz_recordDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnljqjz_recordDashBoardLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lbljqjz_recordDashboard)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnljqjz_recordDashBoardLayout.setVerticalGroup(
            pnljqjz_recordDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnljqjz_recordDashBoardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbljqjz_recordDashboard)
                .addGap(18, 18, 18)
                .addComponent(btnjqjz_recordDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/welcome.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(pnljqjz_inputDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(pnljqjz_recordDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(444, 444, 444))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnljqjz_recordDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnljqjz_inputDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjqjz_inputDashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_inputDashBoardMouseClicked
        // TODO add your handling code here:
        try{
            frmInputs jf = new frmInputs();
        // Display jframe form "frmLoginJQJZ" here
        jf.show();
        // Close current jframe form (frmInputs) after opening frmInputs
        dispose();
        }
        catch(SQLException jqjzE){
                System.out.println("Failed");
                jqjzE.printStackTrace();
            }
    }//GEN-LAST:event_btnjqjz_inputDashBoardMouseClicked

    private void btnjqjz_inputDashBoardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_inputDashBoardMouseEntered
        // TODO add your handling code here:
        pnljqjz_inputDashBoard.setBackground(new java.awt.Color(247,229,214));
    }//GEN-LAST:event_btnjqjz_inputDashBoardMouseEntered

    private void btnjqjz_inputDashBoardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_inputDashBoardMouseExited
        // TODO add your handling code here:
        pnljqjz_inputDashBoard.setBackground(new java.awt.Color(235,218,204));
    }//GEN-LAST:event_btnjqjz_inputDashBoardMouseExited

    private void btnjqjz_inputDashBoardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_inputDashBoardMousePressed
        // TODO add your handling code here:
        pnljqjz_inputDashBoard.setBackground(new java.awt.Color(252,232,200));
    }//GEN-LAST:event_btnjqjz_inputDashBoardMousePressed

    private void btnjqjz_inputDashBoardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_inputDashBoardMouseReleased
        // TODO add your handling code here:
        pnljqjz_inputDashBoard.setBackground(new java.awt.Color(252,232,200));
    }//GEN-LAST:event_btnjqjz_inputDashBoardMouseReleased

    private void btnjqjz_recordDashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_recordDashBoardMouseClicked
        // TODO add your handling code here:
        frmdb jf = new frmdb();
        // Display jframe form "frmLoginJQJZ" here
        jf.show();
        // Close current jframe form (frmInputs) after opening frmInputs
        dispose();
    }//GEN-LAST:event_btnjqjz_recordDashBoardMouseClicked

    private void btnjqjz_recordDashBoardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_recordDashBoardMouseEntered
        // TODO add your handling code here:
        pnljqjz_recordDashBoard.setBackground(new java.awt.Color(247,229,214));
    }//GEN-LAST:event_btnjqjz_recordDashBoardMouseEntered

    private void btnjqjz_recordDashBoardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_recordDashBoardMouseExited
        // TODO add your handling code here:
        pnljqjz_recordDashBoard.setBackground(new java.awt.Color(235,218,204));
    }//GEN-LAST:event_btnjqjz_recordDashBoardMouseExited

    private void btnjqjz_recordDashBoardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_recordDashBoardMousePressed
        // TODO add your handling code here:
        pnljqjz_recordDashBoard.setBackground(new java.awt.Color(252,232,200));
    }//GEN-LAST:event_btnjqjz_recordDashBoardMousePressed

    private void btnjqjz_recordDashBoardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjz_recordDashBoardMouseReleased
        // TODO add your handling code here:
        pnljqjz_recordDashBoard.setBackground(new java.awt.Color(252,232,200));
    }//GEN-LAST:event_btnjqjz_recordDashBoardMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHomeJQJZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHomeJQJZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHomeJQJZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHomeJQJZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHomeJQJZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnjqjz_inputDashBoard;
    private javax.swing.JLabel btnjqjz_recordDashBoard;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbljqjz_inputDashboard;
    private javax.swing.JLabel lbljqjz_recordDashboard;
    private javax.swing.JPanel pnljqjz_inputDashBoard;
    private javax.swing.JPanel pnljqjz_recordDashBoard;
    // End of variables declaration//GEN-END:variables
}
