/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr_bsit1b_it04_jqjz;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import hr_bsit1b_it04_jqjz.jqjzConnect;
import java.awt.Color;
/**
 *
 * @author JLZapanta;
 */
public class frmUserSignUpJQJZ extends javax.swing.JFrame {
    private Statement jqjzstatement;
    public String strjqjzUserID,strjqjzUserName,strjqjzLName,strjqjzFName,strjqjzMName,
                  strjqjzGender,strjqjzUserTypeID,strjqjzEmail,strjqjzPassword;
    public int jqjznumberOfRows;
    jqjzConnect jqjzC = new jqjzConnect();
    Connection jqjzconn;
    PreparedStatement jqjzpreparedStatement;
    String jqjzstrSQL;
    ResultSet jqjzrs;
    /**
     * Creates new form frmUserSignUpJQJZ
     */
    public frmUserSignUpJQJZ() throws SQLException{
        initComponents();
        makeStatement();
        setTitle("Registration Page");
        this.setSize(1366,768); //set display of the current jframe form to 1366x768 resolution
    }
    public Statement makeStatement() throws SQLException{
    jqjzConnect c = new jqjzConnect();
    Connection jqjzconn = c.makeConnection();
    jqjzstatement = jqjzconn.createStatement();
    return jqjzstatement;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jqjzPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbljqjzUserID = new javax.swing.JLabel();
        txtjqjzUserID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtjqjzLName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbljqjzLName = new javax.swing.JLabel();
        lbljqjzFName = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtjqjzEmail = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtjqjzMName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lbljqjzMName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbljqjzPassword = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        lbljqjzEmail = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        lbljqjzUserType = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbljqjzGender = new javax.swing.JLabel();
        pwjqjzPassword = new javax.swing.JPasswordField();
        btnjqjzRegister = new javax.swing.JLabel();
        btnjqjzProceedLogin = new javax.swing.JLabel();
        txtjqjzFName = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        lbljqjzUserName = new javax.swing.JLabel();
        txtjqjzUserName = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txtjqjzGender = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txtjqjzUserTypeID = new javax.swing.JTextField();
        lbljqjzUserInfo = new javax.swing.JLabel();
        lbljqjzIcon = new javax.swing.JLabel();
        lbljqjzApex = new javax.swing.JLabel();
        lbljqjzSignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(175, 102, 37));
        kGradientPanel1.setkGradientFocus(700);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 223, 171));

        jqjzPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbljqjzUserID.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzUserID.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzUserID.setText("User ID");

        txtjqjzUserID.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzUserID.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzUserID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/id.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator1.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        txtjqjzLName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzLName.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzLName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzLName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/user.png"))); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator3.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        lbljqjzLName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzLName.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzLName.setText("Last Name");

        lbljqjzFName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzFName.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzFName.setText("First Name");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/user.png"))); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator4.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        txtjqjzEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzEmail.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jSeparator5.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator5.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        txtjqjzMName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzMName.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzMName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzMName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/user.png"))); // NOI18N

        lbljqjzMName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzMName.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzMName.setText("Middle Name");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/password.png"))); // NOI18N

        lbljqjzPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzPassword.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzPassword.setText("Password");

        jSeparator6.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator6.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/email.png"))); // NOI18N

        lbljqjzEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzEmail.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzEmail.setText("E-mail Address");

        jSeparator7.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator7.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/usertype.png"))); // NOI18N

        lbljqjzUserType.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzUserType.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzUserType.setText("User type ID");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/gender.png"))); // NOI18N

        lbljqjzGender.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzGender.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzGender.setText("Gender");

        pwjqjzPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pwjqjzPassword.setForeground(new java.awt.Color(159, 105, 61));
        pwjqjzPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwjqjzPassword.setBorder(null);

        btnjqjzRegister.setBackground(new java.awt.Color(178, 121, 74));
        btnjqjzRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjqjzRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnjqjzRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjqjzRegister.setText("Register Account");
        btnjqjzRegister.setOpaque(true);
        btnjqjzRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjzRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnjqjzRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnjqjzRegisterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnjqjzRegisterMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnjqjzRegisterMouseReleased(evt);
            }
        });

        btnjqjzProceedLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnjqjzProceedLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjqjzProceedLogin.setForeground(new java.awt.Color(178, 121, 74));
        btnjqjzProceedLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjqjzProceedLogin.setText("Proceed to Login Page");
        btnjqjzProceedLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(178, 121, 74)));
        btnjqjzProceedLogin.setOpaque(true);
        btnjqjzProceedLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjqjzProceedLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnjqjzProceedLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnjqjzProceedLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnjqjzProceedLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnjqjzProceedLoginMouseReleased(evt);
            }
        });

        txtjqjzFName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzFName.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzFName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzFName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jSeparator8.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator8.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/id.png"))); // NOI18N

        lbljqjzUserName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbljqjzUserName.setForeground(new java.awt.Color(178, 121, 74));
        lbljqjzUserName.setText("User Name");

        txtjqjzUserName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzUserName.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jSeparator9.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator9.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        txtjqjzGender.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzGender.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzGender.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        jSeparator10.setBackground(new java.awt.Color(178, 121, 74));
        jSeparator10.setForeground(new java.awt.Color(178, 121, 74));
        jSeparator10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        txtjqjzUserTypeID.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtjqjzUserTypeID.setForeground(new java.awt.Color(178, 121, 74));
        txtjqjzUserTypeID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjqjzUserTypeID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(178, 121, 74)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbljqjzFName)
                    .addComponent(lbljqjzLName)
                    .addComponent(lbljqjzUserID)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjqjzUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbljqjzUserName)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtjqjzUserName))))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lbljqjzMName)
                                .addGap(191, 191, 191))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtjqjzFName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtjqjzLName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtjqjzMName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbljqjzPassword)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pwjqjzPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbljqjzUserType)
                            .addComponent(lbljqjzEmail)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator10)
                                    .addComponent(txtjqjzUserTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbljqjzGender)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator9)
                                    .addComponent(txtjqjzGender, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnjqjzRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator7)
                                        .addComponent(txtjqjzEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnjqjzProceedLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lbljqjzUserID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtjqjzUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(lbljqjzUserName)
                                                .addGap(40, 40, 40))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(txtjqjzUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(1, 1, 1)))
                                .addGap(21, 21, 21)
                                .addComponent(lbljqjzLName)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtjqjzLName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbljqjzGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtjqjzGender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28)
                        .addComponent(lbljqjzFName)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtjqjzFName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbljqjzUserType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtjqjzUserTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbljqjzEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbljqjzMName)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtjqjzMName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtjqjzEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(lbljqjzPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(pwjqjzPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnjqjzRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnjqjzProceedLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        lbljqjzUserInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljqjzUserInfo.setForeground(new java.awt.Color(159, 105, 61));
        lbljqjzUserInfo.setText("User Information");

        lbljqjzIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/logo2_trsp.png"))); // NOI18N

        lbljqjzApex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/company2_trsp.png"))); // NOI18N

        javax.swing.GroupLayout jqjzPanel1Layout = new javax.swing.GroupLayout(jqjzPanel1);
        jqjzPanel1.setLayout(jqjzPanel1Layout);
        jqjzPanel1Layout.setHorizontalGroup(
            jqjzPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jqjzPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(lbljqjzIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbljqjzApex)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jqjzPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbljqjzUserInfo)
                .addGap(240, 240, 240))
            .addGroup(jqjzPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jqjzPanel1Layout.setVerticalGroup(
            jqjzPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jqjzPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jqjzPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbljqjzApex, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbljqjzIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(lbljqjzUserInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        lbljqjzSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr_bsit1b_it04_jqjz/images/tagline2.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbljqjzSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jqjzPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lbljqjzSignUp)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jqjzPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjqjzRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzRegisterMouseClicked
        // TODO add your handling code here:
        if(txtjqjzUserID.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter User ID!");
             txtjqjzUserID.requestFocus();
        }
        else if(txtjqjzUserName.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter User Name!");
             txtjqjzUserName.requestFocus();
        }
        else if(txtjqjzLName.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Last Name!");
             txtjqjzLName.requestFocus();
        }
        else if(txtjqjzFName.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter First Name!");
             txtjqjzFName.requestFocus();
        }
        else if(txtjqjzMName.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Middle Name!");
             txtjqjzMName.requestFocus();
        }
        else if(txtjqjzGender.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Specify Gender!");
             txtjqjzGender.requestFocus();
        }
        else if(txtjqjzUserTypeID.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Specify User Type ID!");
             txtjqjzUserTypeID.requestFocus();
        }
        else if(txtjqjzEmail.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Email Address!");
             txtjqjzEmail.requestFocus();
        }
        else if(pwjqjzPassword.getText().length() == 0){
             JOptionPane.showMessageDialog(null,"Please Enter Password!");
             pwjqjzPassword.requestFocus();
        }
        else{
             try {
                //intID = Integer.parseInt(txtID.getText());
                strjqjzUserID = txtjqjzUserID.getText();
                strjqjzUserName = txtjqjzUserName.getText();
                strjqjzLName = txtjqjzLName.getText();
                strjqjzFName = txtjqjzFName.getText();
                strjqjzMName = txtjqjzMName.getText();
                strjqjzGender = txtjqjzGender.getText();
                strjqjzEmail = txtjqjzEmail.getText();
                strjqjzUserTypeID = txtjqjzUserTypeID.getText();
                strjqjzPassword = pwjqjzPassword.getText();
                
                jqjzconn = jqjzC.makeConnection();
                jqjzstrSQL = "SELECT COUNT(*) AS totRec FROM tbljqjz_user WHERE id=?";
                jqjzpreparedStatement = jqjzconn.prepareStatement(jqjzstrSQL);
                jqjzpreparedStatement.setString(1,strjqjzUserID);
                jqjzrs = jqjzpreparedStatement.executeQuery();
                
                while (jqjzrs.next()) {
                    jqjznumberOfRows = jqjzrs.getInt("totRec");
                    //JOptionPane.showMessageDialog(null, numberOfRows);
                }
                if(jqjznumberOfRows == 1){
                    JOptionPane.showMessageDialog(null, "Record Already Exist!");
                }
                else {
                    String jqjzinsertTableSQL = "INSERT INTO tbljqjz_user"
                    + "(id, User_name, Last_name, First_name, Middle_name, Gender, Email_address, User_type_id, Password) VALUES"
                    + "(?,?,?,?,?,?,?,?,?)";
                    jqjzpreparedStatement = jqjzconn.prepareStatement(jqjzinsertTableSQL);
                    jqjzpreparedStatement.setString(1, strjqjzUserID);
                    jqjzpreparedStatement.setString(2, strjqjzUserName);
                    jqjzpreparedStatement.setString(3, strjqjzLName);
                    jqjzpreparedStatement.setString(4, strjqjzFName);
                    jqjzpreparedStatement.setString(5, strjqjzMName);
                    jqjzpreparedStatement.setString(6, strjqjzGender);
                    jqjzpreparedStatement.setString(7, strjqjzEmail);
                    jqjzpreparedStatement.setString(8, strjqjzUserTypeID);
                    jqjzpreparedStatement.setString(9, strjqjzPassword);
                    // execute insert SQL stetement
                    jqjzpreparedStatement.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Successfully Saved!");
                }
            }
            catch(SQLException jqjzE){
                System.out.println("Failed");
                jqjzE.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnjqjzRegisterMouseClicked

    private void btnjqjzRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzRegisterMouseEntered
        // TODO add your handling code here:
        btnjqjzRegister.setBackground(new java.awt.Color(221, 150, 90));
    }//GEN-LAST:event_btnjqjzRegisterMouseEntered

    private void btnjqjzRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzRegisterMouseExited
        // TODO add your handling code here:
        btnjqjzRegister.setBackground(new java.awt.Color(178,121,74));
    }//GEN-LAST:event_btnjqjzRegisterMouseExited

    private void btnjqjzRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzRegisterMousePressed
        // TODO add your handling code here:
        btnjqjzRegister.setBackground(new java.awt.Color(221, 150, 90));
    }//GEN-LAST:event_btnjqjzRegisterMousePressed

    private void btnjqjzRegisterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzRegisterMouseReleased
        // TODO add your handling code here:
        btnjqjzRegister.setBackground(new java.awt.Color(178,124,90));
    }//GEN-LAST:event_btnjqjzRegisterMouseReleased

    private void btnjqjzProceedLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzProceedLoginMouseClicked
        // TODO add your handling code here:
        // Open jframe form "frmLoginJQJZ"
        try{
            frmLoginJQJZ jf = new frmLoginJQJZ();
        // Display jframe form "frmLoginJQJZ" here
        jf.show();
        // Close current jframe form (frmSignUpJQJZ) after opening frmLoginjqjz
        dispose();
        }
        catch(SQLException jqjzE){
                System.out.println("Failed");
                jqjzE.printStackTrace();
            }
    }//GEN-LAST:event_btnjqjzProceedLoginMouseClicked

    private void btnjqjzProceedLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzProceedLoginMouseEntered
        // TODO add your handling code here:
        btnjqjzProceedLogin.setBackground(new java.awt.Color(178,121,74));
        btnjqjzProceedLogin.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnjqjzProceedLoginMouseEntered

    private void btnjqjzProceedLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzProceedLoginMouseExited
        // TODO add your handling code here:
        btnjqjzProceedLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnjqjzProceedLogin.setForeground(new java.awt.Color(178, 121, 74));
        btnjqjzProceedLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(178, 121, 74)));
    }//GEN-LAST:event_btnjqjzProceedLoginMouseExited

    private void btnjqjzProceedLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzProceedLoginMousePressed
        // TODO add your handling code here:
        btnjqjzProceedLogin.setBackground(new java.awt.Color(178,121,74));
        btnjqjzProceedLogin.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnjqjzProceedLoginMousePressed

    private void btnjqjzProceedLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjqjzProceedLoginMouseReleased
        // TODO add your handling code here:
        btnjqjzRegister.setBackground(new java.awt.Color(178,124,90));
        btnjqjzProceedLogin.setForeground(new java.awt.Color(255,255,255));
        btnjqjzProceedLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(178,124,90)));
    }//GEN-LAST:event_btnjqjzProceedLoginMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUserSignUpJQJZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUserSignUpJQJZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUserSignUpJQJZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUserSignUpJQJZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmUserSignUpJQJZ().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmUserSignUpJQJZ.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnjqjzProceedLogin;
    private javax.swing.JLabel btnjqjzRegister;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel jqjzPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbljqjzApex;
    private javax.swing.JLabel lbljqjzEmail;
    private javax.swing.JLabel lbljqjzFName;
    private javax.swing.JLabel lbljqjzGender;
    private javax.swing.JLabel lbljqjzIcon;
    private javax.swing.JLabel lbljqjzLName;
    private javax.swing.JLabel lbljqjzMName;
    private javax.swing.JLabel lbljqjzPassword;
    private javax.swing.JLabel lbljqjzSignUp;
    private javax.swing.JLabel lbljqjzUserID;
    private javax.swing.JLabel lbljqjzUserInfo;
    private javax.swing.JLabel lbljqjzUserName;
    private javax.swing.JLabel lbljqjzUserType;
    private javax.swing.JPasswordField pwjqjzPassword;
    private javax.swing.JTextField txtjqjzEmail;
    private javax.swing.JTextField txtjqjzFName;
    private javax.swing.JTextField txtjqjzGender;
    private javax.swing.JTextField txtjqjzLName;
    private javax.swing.JTextField txtjqjzMName;
    private javax.swing.JTextField txtjqjzUserID;
    private javax.swing.JTextField txtjqjzUserName;
    private javax.swing.JTextField txtjqjzUserTypeID;
    // End of variables declaration//GEN-END:variables
}
